### ISSUE TITLE
we need SMTP

### ISSUE THREAD

**Issue by tampakrap** [Freeko/Issue-tracker#3]
$subject

**Comment by tampakrap** [comment]
Aug 14 13:05:02 stoupe postfix/smtpd[24561]: warning: connect to private/tlsmgr: No such file or directory
Aug 14 13:05:03 stoupe postfix/smtpd[24561]: warning: connect to private/tlsmgr: No such file or directory
Aug 14 13:05:03 stoupe postfix/smtpd[24561]: warning: problem talking to server private/tlsmgr: No such file or directory
Aug 14 13:05:03 stoupe postfix/smtpd[24561]: warning: no entropy for TLS key generation: disabling TLS support

**Comment by scarabeusiv** [comment]
This was fixed, the other issue prevails

**Comment by tampakrap** [comment]
@scarabeusiv @miska can we close it?

**Comment by scarabeusiv** [comment]
Imo yes, michal fixed it.
