### ISSUE TITLE
api.freeko.org has missing/wrong SSL cert

### ISSUE THREAD

**Issue by mcaj** [Freeko/Issue-tracker#4]
Hi
today I was testing osc on freeko.org and I for SSL error:

see this example:
> alias osck='osc -A https://api.freeko.org'
> osck co home:mcaj/openshot-qt
Certificate Verification Error: Peer certificate subjectAltName does not match host, expected api.freeko.org, got DNS:build.freeko.org, DNS:download.freeko.org, DNS:freeko.org, DNS:mx.freeko.org, DNS:www.freeko.org

I think the DNS cert on the server need to be update to contain also the api url.

Martin

**Comment by scarabeusiv** [comment]
Well, it works because we redirect all traffic, but in the end we use only https://build.freeko.org/ as an api server.

Use -A https://build.freeko.org and it should be enough.

**Comment by tampakrap** [comment]
fixed
